//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OracleEF
{
    using System;
    using System.Collections.Generic;
    
    public partial class APPOINTMENTS
    {
        public decimal OU_ID { get; set; }
        public decimal RESOURCE_ID { get; set; }
        public System.DateTime APPOINTMENTTIME { get; set; }
        public Nullable<decimal> WEB_USER_CODE { get; set; }
        public string CREATE_BY { get; set; }
    }
}
