//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OracleEF
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class OraCnn : DbContext
    {
        public OraCnn()
            : base("name=OraCnn")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<ORGANIZATIONAL_UNITS> ORGANIZATIONAL_UNITS { get; set; }
        public DbSet<OU_RESOURCES> OU_RESOURCES { get; set; }
        public DbSet<OU_SERVICES> OU_SERVICES { get; set; }
        public DbSet<RESOURCES_TYPE> RESOURCES_TYPE { get; set; }
        public DbSet<SERVICES> SERVICES { get; set; }
        public DbSet<APPOINTMENTS> APPOINTMENTS { get; set; }
    }
}
