//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OracleEF
{
    using System;
    using System.Collections.Generic;
    
    public partial class OU_RESOURCES
    {
        public decimal RESOURCE_ID { get; set; }
        public decimal OU_ID { get; set; }
        public string SERVICE_ID { get; set; }
        public Nullable<decimal> RESOURCE_TYPE_ID { get; set; }
        public string RESOURCE_NAME { get; set; }
        public Nullable<decimal> RESOURCE_COUNT { get; set; }
    }
}
