//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OracleEF
{
    using System;
    using System.Collections.Generic;
    
    public partial class RESOURCES_TYPE
    {
        public decimal RESOURCES_TYPE_ID { get; set; }
        public string RESOURCES_TYPE_NAME { get; set; }
    }
}
