//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfAddRef.UserDataWCF {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserDataInfo", Namespace="http://schemas.datacontract.org/2004/07/Riyadh.EServices.Model")]
    [System.SerializableAttribute()]
    public partial class UserDataInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WcfAddRef.UserDataWCF.BaseAddressInfo AddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WcfAddRef.UserDataWCF.BaseContactDataInfo ContactDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DateOfBirthHField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrorCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrorMessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FamilyNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FatherNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FirstNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FullNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private short GenderField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string HifizaNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WcfAddRef.UserDataWCF.BaseIdentityInfo IdentificationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private char LifeStatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int LogIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MeaningMessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NationalityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private short OccupationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OfficeNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OfficeNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private short ReligionCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SponsorMoiNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SubtribeNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ThirdNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserDescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserLoginNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserTypeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WcfAddRef.UserDataWCF.BaseAddressInfo Address {
            get {
                return this.AddressField;
            }
            set {
                if ((object.ReferenceEquals(this.AddressField, value) != true)) {
                    this.AddressField = value;
                    this.RaisePropertyChanged("Address");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WcfAddRef.UserDataWCF.BaseContactDataInfo ContactData {
            get {
                return this.ContactDataField;
            }
            set {
                if ((object.ReferenceEquals(this.ContactDataField, value) != true)) {
                    this.ContactDataField = value;
                    this.RaisePropertyChanged("ContactData");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DateOfBirthH {
            get {
                return this.DateOfBirthHField;
            }
            set {
                if ((object.ReferenceEquals(this.DateOfBirthHField, value) != true)) {
                    this.DateOfBirthHField = value;
                    this.RaisePropertyChanged("DateOfBirthH");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorCode {
            get {
                return this.ErrorCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorCodeField, value) != true)) {
                    this.ErrorCodeField = value;
                    this.RaisePropertyChanged("ErrorCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorMessage {
            get {
                return this.ErrorMessageField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorMessageField, value) != true)) {
                    this.ErrorMessageField = value;
                    this.RaisePropertyChanged("ErrorMessage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FamilyName {
            get {
                return this.FamilyNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FamilyNameField, value) != true)) {
                    this.FamilyNameField = value;
                    this.RaisePropertyChanged("FamilyName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FatherName {
            get {
                return this.FatherNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FatherNameField, value) != true)) {
                    this.FatherNameField = value;
                    this.RaisePropertyChanged("FatherName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FirstName {
            get {
                return this.FirstNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FirstNameField, value) != true)) {
                    this.FirstNameField = value;
                    this.RaisePropertyChanged("FirstName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FullName {
            get {
                return this.FullNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FullNameField, value) != true)) {
                    this.FullNameField = value;
                    this.RaisePropertyChanged("FullName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short Gender {
            get {
                return this.GenderField;
            }
            set {
                if ((this.GenderField.Equals(value) != true)) {
                    this.GenderField = value;
                    this.RaisePropertyChanged("Gender");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string HifizaNumber {
            get {
                return this.HifizaNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.HifizaNumberField, value) != true)) {
                    this.HifizaNumberField = value;
                    this.RaisePropertyChanged("HifizaNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WcfAddRef.UserDataWCF.BaseIdentityInfo Identification {
            get {
                return this.IdentificationField;
            }
            set {
                if ((object.ReferenceEquals(this.IdentificationField, value) != true)) {
                    this.IdentificationField = value;
                    this.RaisePropertyChanged("Identification");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public char LifeStatus {
            get {
                return this.LifeStatusField;
            }
            set {
                if ((this.LifeStatusField.Equals(value) != true)) {
                    this.LifeStatusField = value;
                    this.RaisePropertyChanged("LifeStatus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int LogId {
            get {
                return this.LogIdField;
            }
            set {
                if ((this.LogIdField.Equals(value) != true)) {
                    this.LogIdField = value;
                    this.RaisePropertyChanged("LogId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MeaningMessage {
            get {
                return this.MeaningMessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MeaningMessageField, value) != true)) {
                    this.MeaningMessageField = value;
                    this.RaisePropertyChanged("MeaningMessage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nationality {
            get {
                return this.NationalityField;
            }
            set {
                if ((object.ReferenceEquals(this.NationalityField, value) != true)) {
                    this.NationalityField = value;
                    this.RaisePropertyChanged("Nationality");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short Occupation {
            get {
                return this.OccupationField;
            }
            set {
                if ((this.OccupationField.Equals(value) != true)) {
                    this.OccupationField = value;
                    this.RaisePropertyChanged("Occupation");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OfficeName {
            get {
                return this.OfficeNameField;
            }
            set {
                if ((object.ReferenceEquals(this.OfficeNameField, value) != true)) {
                    this.OfficeNameField = value;
                    this.RaisePropertyChanged("OfficeName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OfficeNo {
            get {
                return this.OfficeNoField;
            }
            set {
                if ((object.ReferenceEquals(this.OfficeNoField, value) != true)) {
                    this.OfficeNoField = value;
                    this.RaisePropertyChanged("OfficeNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short ReligionCode {
            get {
                return this.ReligionCodeField;
            }
            set {
                if ((this.ReligionCodeField.Equals(value) != true)) {
                    this.ReligionCodeField = value;
                    this.RaisePropertyChanged("ReligionCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SponsorMoiNumber {
            get {
                return this.SponsorMoiNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.SponsorMoiNumberField, value) != true)) {
                    this.SponsorMoiNumberField = value;
                    this.RaisePropertyChanged("SponsorMoiNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SubtribeName {
            get {
                return this.SubtribeNameField;
            }
            set {
                if ((object.ReferenceEquals(this.SubtribeNameField, value) != true)) {
                    this.SubtribeNameField = value;
                    this.RaisePropertyChanged("SubtribeName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ThirdName {
            get {
                return this.ThirdNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ThirdNameField, value) != true)) {
                    this.ThirdNameField = value;
                    this.RaisePropertyChanged("ThirdName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserCode {
            get {
                return this.UserCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.UserCodeField, value) != true)) {
                    this.UserCodeField = value;
                    this.RaisePropertyChanged("UserCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserDescription {
            get {
                return this.UserDescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.UserDescriptionField, value) != true)) {
                    this.UserDescriptionField = value;
                    this.RaisePropertyChanged("UserDescription");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserLoginName {
            get {
                return this.UserLoginNameField;
            }
            set {
                if ((object.ReferenceEquals(this.UserLoginNameField, value) != true)) {
                    this.UserLoginNameField = value;
                    this.RaisePropertyChanged("UserLoginName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserType {
            get {
                return this.UserTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.UserTypeField, value) != true)) {
                    this.UserTypeField = value;
                    this.RaisePropertyChanged("UserType");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BaseAddressInfo", Namespace="http://schemas.datacontract.org/2004/07/Riyadh.EServices.Model")]
    [System.SerializableAttribute()]
    public partial class BaseAddressInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BoBoxField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string HouseNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PostalCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WcfAddRef.UserDataWCF.QuarterInfo QuarterField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WcfAddRef.UserDataWCF.StreetInfo StreetField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BoBox {
            get {
                return this.BoBoxField;
            }
            set {
                if ((object.ReferenceEquals(this.BoBoxField, value) != true)) {
                    this.BoBoxField = value;
                    this.RaisePropertyChanged("BoBox");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string HouseNumber {
            get {
                return this.HouseNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.HouseNumberField, value) != true)) {
                    this.HouseNumberField = value;
                    this.RaisePropertyChanged("HouseNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PostalCode {
            get {
                return this.PostalCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.PostalCodeField, value) != true)) {
                    this.PostalCodeField = value;
                    this.RaisePropertyChanged("PostalCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WcfAddRef.UserDataWCF.QuarterInfo Quarter {
            get {
                return this.QuarterField;
            }
            set {
                if ((object.ReferenceEquals(this.QuarterField, value) != true)) {
                    this.QuarterField = value;
                    this.RaisePropertyChanged("Quarter");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WcfAddRef.UserDataWCF.StreetInfo Street {
            get {
                return this.StreetField;
            }
            set {
                if ((object.ReferenceEquals(this.StreetField, value) != true)) {
                    this.StreetField = value;
                    this.RaisePropertyChanged("Street");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BaseContactDataInfo", Namespace="http://schemas.datacontract.org/2004/07/Riyadh.EServices.Model")]
    [System.SerializableAttribute()]
    public partial class BaseContactDataInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FaxNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string HomeTelephonField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MobileField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string WorkTelephonField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FaxNo {
            get {
                return this.FaxNoField;
            }
            set {
                if ((object.ReferenceEquals(this.FaxNoField, value) != true)) {
                    this.FaxNoField = value;
                    this.RaisePropertyChanged("FaxNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string HomeTelephon {
            get {
                return this.HomeTelephonField;
            }
            set {
                if ((object.ReferenceEquals(this.HomeTelephonField, value) != true)) {
                    this.HomeTelephonField = value;
                    this.RaisePropertyChanged("HomeTelephon");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Mobile {
            get {
                return this.MobileField;
            }
            set {
                if ((object.ReferenceEquals(this.MobileField, value) != true)) {
                    this.MobileField = value;
                    this.RaisePropertyChanged("Mobile");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string WorkTelephon {
            get {
                return this.WorkTelephonField;
            }
            set {
                if ((object.ReferenceEquals(this.WorkTelephonField, value) != true)) {
                    this.WorkTelephonField = value;
                    this.RaisePropertyChanged("WorkTelephon");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BaseIdentityInfo", Namespace="http://schemas.datacontract.org/2004/07/Riyadh.EServices.Model")]
    [System.SerializableAttribute()]
    public partial class BaseIdentityInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BorderExpiryDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BorderNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdExpiredDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdIssueDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdIssuePlaceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdentificationNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdentificationTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NationalityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PassportNumberField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BorderExpiryDate {
            get {
                return this.BorderExpiryDateField;
            }
            set {
                if ((object.ReferenceEquals(this.BorderExpiryDateField, value) != true)) {
                    this.BorderExpiryDateField = value;
                    this.RaisePropertyChanged("BorderExpiryDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BorderNumber {
            get {
                return this.BorderNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.BorderNumberField, value) != true)) {
                    this.BorderNumberField = value;
                    this.RaisePropertyChanged("BorderNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IdExpiredDate {
            get {
                return this.IdExpiredDateField;
            }
            set {
                if ((object.ReferenceEquals(this.IdExpiredDateField, value) != true)) {
                    this.IdExpiredDateField = value;
                    this.RaisePropertyChanged("IdExpiredDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IdIssueDate {
            get {
                return this.IdIssueDateField;
            }
            set {
                if ((object.ReferenceEquals(this.IdIssueDateField, value) != true)) {
                    this.IdIssueDateField = value;
                    this.RaisePropertyChanged("IdIssueDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IdIssuePlace {
            get {
                return this.IdIssuePlaceField;
            }
            set {
                if ((object.ReferenceEquals(this.IdIssuePlaceField, value) != true)) {
                    this.IdIssuePlaceField = value;
                    this.RaisePropertyChanged("IdIssuePlace");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IdentificationNo {
            get {
                return this.IdentificationNoField;
            }
            set {
                if ((object.ReferenceEquals(this.IdentificationNoField, value) != true)) {
                    this.IdentificationNoField = value;
                    this.RaisePropertyChanged("IdentificationNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IdentificationType {
            get {
                return this.IdentificationTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.IdentificationTypeField, value) != true)) {
                    this.IdentificationTypeField = value;
                    this.RaisePropertyChanged("IdentificationType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nationality {
            get {
                return this.NationalityField;
            }
            set {
                if ((object.ReferenceEquals(this.NationalityField, value) != true)) {
                    this.NationalityField = value;
                    this.RaisePropertyChanged("Nationality");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PassportNumber {
            get {
                return this.PassportNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.PassportNumberField, value) != true)) {
                    this.PassportNumberField = value;
                    this.RaisePropertyChanged("PassportNumber");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="QuarterInfo", Namespace="http://schemas.datacontract.org/2004/07/Riyadh.EServices.Model")]
    [System.SerializableAttribute()]
    public partial class QuarterInfo : WcfAddRef.UserDataWCF.BaseInfo {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AreaCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DirectoratCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameNumbrerField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AreaCode {
            get {
                return this.AreaCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.AreaCodeField, value) != true)) {
                    this.AreaCodeField = value;
                    this.RaisePropertyChanged("AreaCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DirectoratCode {
            get {
                return this.DirectoratCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.DirectoratCodeField, value) != true)) {
                    this.DirectoratCodeField = value;
                    this.RaisePropertyChanged("DirectoratCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NameNumbrer {
            get {
                return this.NameNumbrerField;
            }
            set {
                if ((object.ReferenceEquals(this.NameNumbrerField, value) != true)) {
                    this.NameNumbrerField = value;
                    this.RaisePropertyChanged("NameNumbrer");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="StreetInfo", Namespace="http://schemas.datacontract.org/2004/07/Riyadh.EServices.Model")]
    [System.SerializableAttribute()]
    public partial class StreetInfo : WcfAddRef.UserDataWCF.BaseInfo {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string QuarterCodeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string QuarterCode {
            get {
                return this.QuarterCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.QuarterCodeField, value) != true)) {
                    this.QuarterCodeField = value;
                    this.RaisePropertyChanged("QuarterCode");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BaseInfo", Namespace="http://schemas.datacontract.org/2004/07/Riyadh.EServices.Model")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WcfAddRef.UserDataWCF.StreetInfo))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WcfAddRef.UserDataWCF.DirectionInfo))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WcfAddRef.UserDataWCF.QuarterInfo))]
    public partial class BaseInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CreatedByField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CreatedDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ModifiedByField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ModifiedDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Code {
            get {
                return this.CodeField;
            }
            set {
                if ((object.ReferenceEquals(this.CodeField, value) != true)) {
                    this.CodeField = value;
                    this.RaisePropertyChanged("Code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CreatedBy {
            get {
                return this.CreatedByField;
            }
            set {
                if ((object.ReferenceEquals(this.CreatedByField, value) != true)) {
                    this.CreatedByField = value;
                    this.RaisePropertyChanged("CreatedBy");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CreatedDate {
            get {
                return this.CreatedDateField;
            }
            set {
                if ((object.ReferenceEquals(this.CreatedDateField, value) != true)) {
                    this.CreatedDateField = value;
                    this.RaisePropertyChanged("CreatedDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ModifiedBy {
            get {
                return this.ModifiedByField;
            }
            set {
                if ((object.ReferenceEquals(this.ModifiedByField, value) != true)) {
                    this.ModifiedByField = value;
                    this.RaisePropertyChanged("ModifiedBy");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ModifiedDate {
            get {
                return this.ModifiedDateField;
            }
            set {
                if ((object.ReferenceEquals(this.ModifiedDateField, value) != true)) {
                    this.ModifiedDateField = value;
                    this.RaisePropertyChanged("ModifiedDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DirectionInfo", Namespace="http://schemas.datacontract.org/2004/07/Riyadh.EServices.Model")]
    [System.SerializableAttribute()]
    public partial class DirectionInfo : WcfAddRef.UserDataWCF.BaseInfo {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AmanaOverdueInfo", Namespace="http://schemas.datacontract.org/2004/07/Riyadh.EServices.Model")]
    [System.SerializableAttribute()]
    public partial class AmanaOverdueInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AppTypeDescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ApplicationDescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BillAccountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BillDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WcfAddRef.UserDataWCF.DirectionInfo DirectionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal FormAmountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WcfAddRef.UserDataWCF.BaseIdentityInfo OwnerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RemarksField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AppTypeDescription {
            get {
                return this.AppTypeDescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.AppTypeDescriptionField, value) != true)) {
                    this.AppTypeDescriptionField = value;
                    this.RaisePropertyChanged("AppTypeDescription");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ApplicationDescription {
            get {
                return this.ApplicationDescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.ApplicationDescriptionField, value) != true)) {
                    this.ApplicationDescriptionField = value;
                    this.RaisePropertyChanged("ApplicationDescription");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BillAccount {
            get {
                return this.BillAccountField;
            }
            set {
                if ((object.ReferenceEquals(this.BillAccountField, value) != true)) {
                    this.BillAccountField = value;
                    this.RaisePropertyChanged("BillAccount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BillDate {
            get {
                return this.BillDateField;
            }
            set {
                if ((object.ReferenceEquals(this.BillDateField, value) != true)) {
                    this.BillDateField = value;
                    this.RaisePropertyChanged("BillDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WcfAddRef.UserDataWCF.DirectionInfo Direction {
            get {
                return this.DirectionField;
            }
            set {
                if ((object.ReferenceEquals(this.DirectionField, value) != true)) {
                    this.DirectionField = value;
                    this.RaisePropertyChanged("Direction");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal FormAmount {
            get {
                return this.FormAmountField;
            }
            set {
                if ((this.FormAmountField.Equals(value) != true)) {
                    this.FormAmountField = value;
                    this.RaisePropertyChanged("FormAmount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WcfAddRef.UserDataWCF.BaseIdentityInfo Owner {
            get {
                return this.OwnerField;
            }
            set {
                if ((object.ReferenceEquals(this.OwnerField, value) != true)) {
                    this.OwnerField = value;
                    this.RaisePropertyChanged("Owner");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Remarks {
            get {
                return this.RemarksField;
            }
            set {
                if ((object.ReferenceEquals(this.RemarksField, value) != true)) {
                    this.RemarksField = value;
                    this.RaisePropertyChanged("Remarks");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="UserDataWCF.IUser")]
    public interface IUser {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUser/GetEmployeeList", ReplyAction="http://tempuri.org/IUser/GetEmployeeListResponse")]
        System.Collections.Generic.List<WcfAddRef.UserDataWCF.UserDataInfo> GetEmployeeList(string userCode, string name, string email, string mobile);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUser/GetEmployeeList", ReplyAction="http://tempuri.org/IUser/GetEmployeeListResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<WcfAddRef.UserDataWCF.UserDataInfo>> GetEmployeeListAsync(string userCode, string name, string email, string mobile);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUser/GetCmnUserData", ReplyAction="http://tempuri.org/IUser/GetCmnUserDataResponse")]
        WcfAddRef.UserDataWCF.UserDataInfo GetCmnUserData(string userCode, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUser/GetCmnUserData", ReplyAction="http://tempuri.org/IUser/GetCmnUserDataResponse")]
        System.Threading.Tasks.Task<WcfAddRef.UserDataWCF.UserDataInfo> GetCmnUserDataAsync(string userCode, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUser/CheckAmanaHasOverdue", ReplyAction="http://tempuri.org/IUser/CheckAmanaHasOverdueResponse")]
        string CheckAmanaHasOverdue(int ownerType, string ownerNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUser/CheckAmanaHasOverdue", ReplyAction="http://tempuri.org/IUser/CheckAmanaHasOverdueResponse")]
        System.Threading.Tasks.Task<string> CheckAmanaHasOverdueAsync(int ownerType, string ownerNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUser/GetAmanaOverdue", ReplyAction="http://tempuri.org/IUser/GetAmanaOverdueResponse")]
        System.Collections.Generic.List<WcfAddRef.UserDataWCF.AmanaOverdueInfo> GetAmanaOverdue(int ownerType, string ownerNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUser/GetAmanaOverdue", ReplyAction="http://tempuri.org/IUser/GetAmanaOverdueResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<WcfAddRef.UserDataWCF.AmanaOverdueInfo>> GetAmanaOverdueAsync(int ownerType, string ownerNumber);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IUserChannel : WcfAddRef.UserDataWCF.IUser, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class UserClient : System.ServiceModel.ClientBase<WcfAddRef.UserDataWCF.IUser>, WcfAddRef.UserDataWCF.IUser {
        
        public UserClient() {
        }
        
        public UserClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public UserClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UserClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UserClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Collections.Generic.List<WcfAddRef.UserDataWCF.UserDataInfo> GetEmployeeList(string userCode, string name, string email, string mobile) {
            return base.Channel.GetEmployeeList(userCode, name, email, mobile);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<WcfAddRef.UserDataWCF.UserDataInfo>> GetEmployeeListAsync(string userCode, string name, string email, string mobile) {
            return base.Channel.GetEmployeeListAsync(userCode, name, email, mobile);
        }
        
        public WcfAddRef.UserDataWCF.UserDataInfo GetCmnUserData(string userCode, string password) {
            return base.Channel.GetCmnUserData(userCode, password);
        }
        
        public System.Threading.Tasks.Task<WcfAddRef.UserDataWCF.UserDataInfo> GetCmnUserDataAsync(string userCode, string password) {
            return base.Channel.GetCmnUserDataAsync(userCode, password);
        }
        
        public string CheckAmanaHasOverdue(int ownerType, string ownerNumber) {
            return base.Channel.CheckAmanaHasOverdue(ownerType, ownerNumber);
        }
        
        public System.Threading.Tasks.Task<string> CheckAmanaHasOverdueAsync(int ownerType, string ownerNumber) {
            return base.Channel.CheckAmanaHasOverdueAsync(ownerType, ownerNumber);
        }
        
        public System.Collections.Generic.List<WcfAddRef.UserDataWCF.AmanaOverdueInfo> GetAmanaOverdue(int ownerType, string ownerNumber) {
            return base.Channel.GetAmanaOverdue(ownerType, ownerNumber);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<WcfAddRef.UserDataWCF.AmanaOverdueInfo>> GetAmanaOverdueAsync(int ownerType, string ownerNumber) {
            return base.Channel.GetAmanaOverdueAsync(ownerType, ownerNumber);
        }
    }
}
