//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.34209.
// 
#pragma warning disable 1591

namespace WebServiceClient.WebService1 {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="WebService1Soap", Namespace="http://tempuri.org/")]
    public partial class WebService1 : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private Password passwordValueField;
        
        private UserName userNameValueField;
        
        private System.Threading.SendOrPostCallback HelloWorldOperationCompleted;
        
        private System.Threading.SendOrPostCallback AddAmanahResponseOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public WebService1() {
            this.Url = global::WebServiceClient.Properties.Settings.Default.WebServiceClient_WebService1_WebService1;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public Password PasswordValue {
            get {
                return this.passwordValueField;
            }
            set {
                this.passwordValueField = value;
            }
        }
        
        public UserName UserNameValue {
            get {
                return this.userNameValueField;
            }
            set {
                this.userNameValueField = value;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event HelloWorldCompletedEventHandler HelloWorldCompleted;
        
        /// <remarks/>
        public event AddAmanahResponseCompletedEventHandler AddAmanahResponseCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("UserNameValue")]
        [System.Web.Services.Protocols.SoapHeaderAttribute("PasswordValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/HelloWorld", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string HelloWorld(string _data) {
            object[] results = this.Invoke("HelloWorld", new object[] {
                        _data});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void HelloWorldAsync(string _data) {
            this.HelloWorldAsync(_data, null);
        }
        
        /// <remarks/>
        public void HelloWorldAsync(string _data, object userState) {
            if ((this.HelloWorldOperationCompleted == null)) {
                this.HelloWorldOperationCompleted = new System.Threading.SendOrPostCallback(this.OnHelloWorldOperationCompleted);
            }
            this.InvokeAsync("HelloWorld", new object[] {
                        _data}, this.HelloWorldOperationCompleted, userState);
        }
        
        private void OnHelloWorldOperationCompleted(object arg) {
            if ((this.HelloWorldCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.HelloWorldCompleted(this, new HelloWorldCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("UserNameValue")]
        [System.Web.Services.Protocols.SoapHeaderAttribute("PasswordValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/AddAmanahResponse", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void AddAmanahResponse(int CardStatus, [System.Xml.Serialization.XmlIgnoreAttribute()] bool CardStatusSpecified, int CerResultID, [System.Xml.Serialization.XmlIgnoreAttribute()] bool CerResultIDSpecified, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string CertificateCard_ID, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string CertificateExpire_Date, int ClientResponseStatus, [System.Xml.Serialization.XmlIgnoreAttribute()] bool ClientResponseStatusSpecified, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string Remarks, out short ResultCode, [System.Xml.Serialization.XmlIgnoreAttribute()] out bool ResultCodeSpecified, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] out string ResultMessage) {
            object[] results = this.Invoke("AddAmanahResponse", new object[] {
                        CardStatus,
                        CardStatusSpecified,
                        CerResultID,
                        CerResultIDSpecified,
                        CertificateCard_ID,
                        CertificateExpire_Date,
                        ClientResponseStatus,
                        ClientResponseStatusSpecified,
                        Remarks});
            ResultCode = ((short)(results[0]));
            ResultCodeSpecified = ((bool)(results[1]));
            ResultMessage = ((string)(results[2]));
        }
        
        /// <remarks/>
        public void AddAmanahResponseAsync(int CardStatus, bool CardStatusSpecified, int CerResultID, bool CerResultIDSpecified, string CertificateCard_ID, string CertificateExpire_Date, int ClientResponseStatus, bool ClientResponseStatusSpecified, string Remarks) {
            this.AddAmanahResponseAsync(CardStatus, CardStatusSpecified, CerResultID, CerResultIDSpecified, CertificateCard_ID, CertificateExpire_Date, ClientResponseStatus, ClientResponseStatusSpecified, Remarks, null);
        }
        
        /// <remarks/>
        public void AddAmanahResponseAsync(int CardStatus, bool CardStatusSpecified, int CerResultID, bool CerResultIDSpecified, string CertificateCard_ID, string CertificateExpire_Date, int ClientResponseStatus, bool ClientResponseStatusSpecified, string Remarks, object userState) {
            if ((this.AddAmanahResponseOperationCompleted == null)) {
                this.AddAmanahResponseOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAddAmanahResponseOperationCompleted);
            }
            this.InvokeAsync("AddAmanahResponse", new object[] {
                        CardStatus,
                        CardStatusSpecified,
                        CerResultID,
                        CerResultIDSpecified,
                        CertificateCard_ID,
                        CertificateExpire_Date,
                        ClientResponseStatus,
                        ClientResponseStatusSpecified,
                        Remarks}, this.AddAmanahResponseOperationCompleted, userState);
        }
        
        private void OnAddAmanahResponseOperationCompleted(object arg) {
            if ((this.AddAmanahResponseCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AddAmanahResponseCompleted(this, new AddAmanahResponseCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://tempuri.org/", IsNullable=false)]
    public partial class UserName : System.Web.Services.Protocols.SoapHeader {
        
        private string[] textField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <remarks/>
        public string[] Text {
            get {
                return this.textField;
            }
            set {
                this.textField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://tempuri.org/", IsNullable=false)]
    public partial class Password : System.Web.Services.Protocols.SoapHeader {
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        private string[] textField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string[] Text {
            get {
                return this.textField;
            }
            set {
                this.textField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    public delegate void HelloWorldCompletedEventHandler(object sender, HelloWorldCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class HelloWorldCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal HelloWorldCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    public delegate void AddAmanahResponseCompletedEventHandler(object sender, AddAmanahResponseCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AddAmanahResponseCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AddAmanahResponseCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public short ResultCode {
            get {
                this.RaiseExceptionIfNecessary();
                return ((short)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public bool ResultCodeSpecified {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[1]));
            }
        }
        
        /// <remarks/>
        public string ResultMessage {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[2]));
            }
        }
    }
}

#pragma warning restore 1591