//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CallWcfTest.DocFlowWCF {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DocSearchParameters", Namespace="http://schemas.datacontract.org/2004/07/Riyadh.EServices.Model.DocFlow")]
    [System.SerializableAttribute()]
    public partial class DocSearchParameters : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int AssignToEmployeeCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ConfirmationUserCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> CreateByDepartmentCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> DocFromDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DocReferenceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DocSubjectField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> DocToDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FromOrganisationOrCitizenField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> IsSubmittedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> TransferFromDepartmentCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> TransferNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> TransferToDepartmentCodeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int AssignToEmployeeCode {
            get {
                return this.AssignToEmployeeCodeField;
            }
            set {
                if ((this.AssignToEmployeeCodeField.Equals(value) != true)) {
                    this.AssignToEmployeeCodeField = value;
                    this.RaisePropertyChanged("AssignToEmployeeCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ConfirmationUserCode {
            get {
                return this.ConfirmationUserCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.ConfirmationUserCodeField, value) != true)) {
                    this.ConfirmationUserCodeField = value;
                    this.RaisePropertyChanged("ConfirmationUserCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> CreateByDepartmentCode {
            get {
                return this.CreateByDepartmentCodeField;
            }
            set {
                if ((this.CreateByDepartmentCodeField.Equals(value) != true)) {
                    this.CreateByDepartmentCodeField = value;
                    this.RaisePropertyChanged("CreateByDepartmentCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> DocFromDate {
            get {
                return this.DocFromDateField;
            }
            set {
                if ((this.DocFromDateField.Equals(value) != true)) {
                    this.DocFromDateField = value;
                    this.RaisePropertyChanged("DocFromDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DocReference {
            get {
                return this.DocReferenceField;
            }
            set {
                if ((object.ReferenceEquals(this.DocReferenceField, value) != true)) {
                    this.DocReferenceField = value;
                    this.RaisePropertyChanged("DocReference");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DocSubject {
            get {
                return this.DocSubjectField;
            }
            set {
                if ((object.ReferenceEquals(this.DocSubjectField, value) != true)) {
                    this.DocSubjectField = value;
                    this.RaisePropertyChanged("DocSubject");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> DocToDate {
            get {
                return this.DocToDateField;
            }
            set {
                if ((this.DocToDateField.Equals(value) != true)) {
                    this.DocToDateField = value;
                    this.RaisePropertyChanged("DocToDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FromOrganisationOrCitizen {
            get {
                return this.FromOrganisationOrCitizenField;
            }
            set {
                if ((object.ReferenceEquals(this.FromOrganisationOrCitizenField, value) != true)) {
                    this.FromOrganisationOrCitizenField = value;
                    this.RaisePropertyChanged("FromOrganisationOrCitizen");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> IsSubmitted {
            get {
                return this.IsSubmittedField;
            }
            set {
                if ((this.IsSubmittedField.Equals(value) != true)) {
                    this.IsSubmittedField = value;
                    this.RaisePropertyChanged("IsSubmitted");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> TransferFromDepartmentCode {
            get {
                return this.TransferFromDepartmentCodeField;
            }
            set {
                if ((this.TransferFromDepartmentCodeField.Equals(value) != true)) {
                    this.TransferFromDepartmentCodeField = value;
                    this.RaisePropertyChanged("TransferFromDepartmentCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> TransferNumber {
            get {
                return this.TransferNumberField;
            }
            set {
                if ((this.TransferNumberField.Equals(value) != true)) {
                    this.TransferNumberField = value;
                    this.RaisePropertyChanged("TransferNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> TransferToDepartmentCode {
            get {
                return this.TransferToDepartmentCodeField;
            }
            set {
                if ((this.TransferToDepartmentCodeField.Equals(value) != true)) {
                    this.TransferToDepartmentCodeField = value;
                    this.RaisePropertyChanged("TransferToDepartmentCode");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DocFlowInfo", Namespace="http://schemas.datacontract.org/2004/07/Riyadh.EServices.Model.DocFlow")]
    [System.SerializableAttribute()]
    public partial class DocFlowInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime AddDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AddUserField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int AttachmentsNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> ConfirmationDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ConfirmationUserCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DocumentStatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DocumentTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string HeaderField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IsCanceledField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IsClosedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IsReceivedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IsRejectedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> IsSubmittedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LetterContentsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int NotificationDaysField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime ReceivedDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ReceivedDateHejryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ReferenceNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SubjectField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TotalRowCountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime TransferDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TransferDateHejryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TransferFromField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TransferFromDepartmentCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TransferFromOrganisationCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TransferNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TransferParentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TransferToField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TransferToDepartmentCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TransferToOrganisationCodeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime AddDate {
            get {
                return this.AddDateField;
            }
            set {
                if ((this.AddDateField.Equals(value) != true)) {
                    this.AddDateField = value;
                    this.RaisePropertyChanged("AddDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AddUser {
            get {
                return this.AddUserField;
            }
            set {
                if ((object.ReferenceEquals(this.AddUserField, value) != true)) {
                    this.AddUserField = value;
                    this.RaisePropertyChanged("AddUser");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int AttachmentsNo {
            get {
                return this.AttachmentsNoField;
            }
            set {
                if ((this.AttachmentsNoField.Equals(value) != true)) {
                    this.AttachmentsNoField = value;
                    this.RaisePropertyChanged("AttachmentsNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> ConfirmationDate {
            get {
                return this.ConfirmationDateField;
            }
            set {
                if ((this.ConfirmationDateField.Equals(value) != true)) {
                    this.ConfirmationDateField = value;
                    this.RaisePropertyChanged("ConfirmationDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ConfirmationUserCode {
            get {
                return this.ConfirmationUserCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.ConfirmationUserCodeField, value) != true)) {
                    this.ConfirmationUserCodeField = value;
                    this.RaisePropertyChanged("ConfirmationUserCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DocumentStatus {
            get {
                return this.DocumentStatusField;
            }
            set {
                if ((object.ReferenceEquals(this.DocumentStatusField, value) != true)) {
                    this.DocumentStatusField = value;
                    this.RaisePropertyChanged("DocumentStatus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DocumentType {
            get {
                return this.DocumentTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.DocumentTypeField, value) != true)) {
                    this.DocumentTypeField = value;
                    this.RaisePropertyChanged("DocumentType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Header {
            get {
                return this.HeaderField;
            }
            set {
                if ((object.ReferenceEquals(this.HeaderField, value) != true)) {
                    this.HeaderField = value;
                    this.RaisePropertyChanged("Header");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IsCanceled {
            get {
                return this.IsCanceledField;
            }
            set {
                if ((this.IsCanceledField.Equals(value) != true)) {
                    this.IsCanceledField = value;
                    this.RaisePropertyChanged("IsCanceled");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IsClosed {
            get {
                return this.IsClosedField;
            }
            set {
                if ((this.IsClosedField.Equals(value) != true)) {
                    this.IsClosedField = value;
                    this.RaisePropertyChanged("IsClosed");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IsReceived {
            get {
                return this.IsReceivedField;
            }
            set {
                if ((this.IsReceivedField.Equals(value) != true)) {
                    this.IsReceivedField = value;
                    this.RaisePropertyChanged("IsReceived");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IsRejected {
            get {
                return this.IsRejectedField;
            }
            set {
                if ((this.IsRejectedField.Equals(value) != true)) {
                    this.IsRejectedField = value;
                    this.RaisePropertyChanged("IsRejected");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> IsSubmitted {
            get {
                return this.IsSubmittedField;
            }
            set {
                if ((this.IsSubmittedField.Equals(value) != true)) {
                    this.IsSubmittedField = value;
                    this.RaisePropertyChanged("IsSubmitted");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LetterContents {
            get {
                return this.LetterContentsField;
            }
            set {
                if ((object.ReferenceEquals(this.LetterContentsField, value) != true)) {
                    this.LetterContentsField = value;
                    this.RaisePropertyChanged("LetterContents");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int NotificationDays {
            get {
                return this.NotificationDaysField;
            }
            set {
                if ((this.NotificationDaysField.Equals(value) != true)) {
                    this.NotificationDaysField = value;
                    this.RaisePropertyChanged("NotificationDays");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime ReceivedDate {
            get {
                return this.ReceivedDateField;
            }
            set {
                if ((this.ReceivedDateField.Equals(value) != true)) {
                    this.ReceivedDateField = value;
                    this.RaisePropertyChanged("ReceivedDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ReceivedDateHejry {
            get {
                return this.ReceivedDateHejryField;
            }
            set {
                if ((object.ReferenceEquals(this.ReceivedDateHejryField, value) != true)) {
                    this.ReceivedDateHejryField = value;
                    this.RaisePropertyChanged("ReceivedDateHejry");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ReferenceNo {
            get {
                return this.ReferenceNoField;
            }
            set {
                if ((object.ReferenceEquals(this.ReferenceNoField, value) != true)) {
                    this.ReferenceNoField = value;
                    this.RaisePropertyChanged("ReferenceNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Subject {
            get {
                return this.SubjectField;
            }
            set {
                if ((object.ReferenceEquals(this.SubjectField, value) != true)) {
                    this.SubjectField = value;
                    this.RaisePropertyChanged("Subject");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TotalRowCount {
            get {
                return this.TotalRowCountField;
            }
            set {
                if ((this.TotalRowCountField.Equals(value) != true)) {
                    this.TotalRowCountField = value;
                    this.RaisePropertyChanged("TotalRowCount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime TransferDate {
            get {
                return this.TransferDateField;
            }
            set {
                if ((this.TransferDateField.Equals(value) != true)) {
                    this.TransferDateField = value;
                    this.RaisePropertyChanged("TransferDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TransferDateHejry {
            get {
                return this.TransferDateHejryField;
            }
            set {
                if ((object.ReferenceEquals(this.TransferDateHejryField, value) != true)) {
                    this.TransferDateHejryField = value;
                    this.RaisePropertyChanged("TransferDateHejry");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TransferFrom {
            get {
                return this.TransferFromField;
            }
            set {
                if ((object.ReferenceEquals(this.TransferFromField, value) != true)) {
                    this.TransferFromField = value;
                    this.RaisePropertyChanged("TransferFrom");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TransferFromDepartmentCode {
            get {
                return this.TransferFromDepartmentCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.TransferFromDepartmentCodeField, value) != true)) {
                    this.TransferFromDepartmentCodeField = value;
                    this.RaisePropertyChanged("TransferFromDepartmentCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TransferFromOrganisationCode {
            get {
                return this.TransferFromOrganisationCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.TransferFromOrganisationCodeField, value) != true)) {
                    this.TransferFromOrganisationCodeField = value;
                    this.RaisePropertyChanged("TransferFromOrganisationCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TransferNumber {
            get {
                return this.TransferNumberField;
            }
            set {
                if ((this.TransferNumberField.Equals(value) != true)) {
                    this.TransferNumberField = value;
                    this.RaisePropertyChanged("TransferNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TransferParent {
            get {
                return this.TransferParentField;
            }
            set {
                if ((object.ReferenceEquals(this.TransferParentField, value) != true)) {
                    this.TransferParentField = value;
                    this.RaisePropertyChanged("TransferParent");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TransferTo {
            get {
                return this.TransferToField;
            }
            set {
                if ((object.ReferenceEquals(this.TransferToField, value) != true)) {
                    this.TransferToField = value;
                    this.RaisePropertyChanged("TransferTo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TransferToDepartmentCode {
            get {
                return this.TransferToDepartmentCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.TransferToDepartmentCodeField, value) != true)) {
                    this.TransferToDepartmentCodeField = value;
                    this.RaisePropertyChanged("TransferToDepartmentCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TransferToOrganisationCode {
            get {
                return this.TransferToOrganisationCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.TransferToOrganisationCodeField, value) != true)) {
                    this.TransferToOrganisationCodeField = value;
                    this.RaisePropertyChanged("TransferToOrganisationCode");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Department", Namespace="http://schemas.datacontract.org/2004/07/Riyadh.EServices.Model.DocFlow")]
    [System.SerializableAttribute()]
    public partial class Department : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DepartmentCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DepartmentNameArField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DepartmentCode {
            get {
                return this.DepartmentCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.DepartmentCodeField, value) != true)) {
                    this.DepartmentCodeField = value;
                    this.RaisePropertyChanged("DepartmentCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DepartmentNameAr {
            get {
                return this.DepartmentNameArField;
            }
            set {
                if ((object.ReferenceEquals(this.DepartmentNameArField, value) != true)) {
                    this.DepartmentNameArField = value;
                    this.RaisePropertyChanged("DepartmentNameAr");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Organization", Namespace="http://schemas.datacontract.org/2004/07/Riyadh.EServices.Model.DocFlow")]
    [System.SerializableAttribute()]
    public partial class Organization : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OrganizationCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OrganizationNameArField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OrganizationCode {
            get {
                return this.OrganizationCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.OrganizationCodeField, value) != true)) {
                    this.OrganizationCodeField = value;
                    this.RaisePropertyChanged("OrganizationCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OrganizationNameAr {
            get {
                return this.OrganizationNameArField;
            }
            set {
                if ((object.ReferenceEquals(this.OrganizationNameArField, value) != true)) {
                    this.OrganizationNameArField = value;
                    this.RaisePropertyChanged("OrganizationNameAr");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EmployeeInfo", Namespace="http://schemas.datacontract.org/2004/07/Riyadh.EServices.Model.DocFlow")]
    [System.SerializableAttribute()]
    public partial class EmployeeInfo : CallWcfTest.DocFlowWCF.BaseInfo {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DirectorateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FullNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MobileField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserCodeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Address {
            get {
                return this.AddressField;
            }
            set {
                if ((object.ReferenceEquals(this.AddressField, value) != true)) {
                    this.AddressField = value;
                    this.RaisePropertyChanged("Address");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Directorate {
            get {
                return this.DirectorateField;
            }
            set {
                if ((object.ReferenceEquals(this.DirectorateField, value) != true)) {
                    this.DirectorateField = value;
                    this.RaisePropertyChanged("Directorate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FullName {
            get {
                return this.FullNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FullNameField, value) != true)) {
                    this.FullNameField = value;
                    this.RaisePropertyChanged("FullName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Mobile {
            get {
                return this.MobileField;
            }
            set {
                if ((object.ReferenceEquals(this.MobileField, value) != true)) {
                    this.MobileField = value;
                    this.RaisePropertyChanged("Mobile");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserCode {
            get {
                return this.UserCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.UserCodeField, value) != true)) {
                    this.UserCodeField = value;
                    this.RaisePropertyChanged("UserCode");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BaseInfo", Namespace="http://schemas.datacontract.org/2004/07/Riyadh.EServices.Model")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(CallWcfTest.DocFlowWCF.EmployeeInfo))]
    public partial class BaseInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CreatedByField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CreatedDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ModifiedByField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ModifiedDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Code {
            get {
                return this.CodeField;
            }
            set {
                if ((object.ReferenceEquals(this.CodeField, value) != true)) {
                    this.CodeField = value;
                    this.RaisePropertyChanged("Code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CreatedBy {
            get {
                return this.CreatedByField;
            }
            set {
                if ((object.ReferenceEquals(this.CreatedByField, value) != true)) {
                    this.CreatedByField = value;
                    this.RaisePropertyChanged("CreatedBy");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CreatedDate {
            get {
                return this.CreatedDateField;
            }
            set {
                if ((object.ReferenceEquals(this.CreatedDateField, value) != true)) {
                    this.CreatedDateField = value;
                    this.RaisePropertyChanged("CreatedDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ModifiedBy {
            get {
                return this.ModifiedByField;
            }
            set {
                if ((object.ReferenceEquals(this.ModifiedByField, value) != true)) {
                    this.ModifiedByField = value;
                    this.RaisePropertyChanged("ModifiedBy");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ModifiedDate {
            get {
                return this.ModifiedDateField;
            }
            set {
                if ((object.ReferenceEquals(this.ModifiedDateField, value) != true)) {
                    this.ModifiedDateField = value;
                    this.RaisePropertyChanged("ModifiedDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LetterTemplate", Namespace="http://schemas.datacontract.org/2004/07/Riyadh.EServices.Model.DocFlow")]
    [System.SerializableAttribute()]
    public partial class LetterTemplate : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int DirCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TemplateCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TemplateDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TemplateNameArField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int DirCode {
            get {
                return this.DirCodeField;
            }
            set {
                if ((this.DirCodeField.Equals(value) != true)) {
                    this.DirCodeField = value;
                    this.RaisePropertyChanged("DirCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TemplateCode {
            get {
                return this.TemplateCodeField;
            }
            set {
                if ((this.TemplateCodeField.Equals(value) != true)) {
                    this.TemplateCodeField = value;
                    this.RaisePropertyChanged("TemplateCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TemplateData {
            get {
                return this.TemplateDataField;
            }
            set {
                if ((object.ReferenceEquals(this.TemplateDataField, value) != true)) {
                    this.TemplateDataField = value;
                    this.RaisePropertyChanged("TemplateData");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TemplateNameAr {
            get {
                return this.TemplateNameArField;
            }
            set {
                if ((object.ReferenceEquals(this.TemplateNameArField, value) != true)) {
                    this.TemplateNameArField = value;
                    this.RaisePropertyChanged("TemplateNameAr");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SaveResult", Namespace="http://schemas.datacontract.org/2004/07/Riyadh.EServices.Model")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(CallWcfTest.DocFlowWCF.DocSearchParameters))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(CallWcfTest.DocFlowWCF.DocFlowInfo[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(CallWcfTest.DocFlowWCF.DocFlowInfo))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(CallWcfTest.DocFlowWCF.Department[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(CallWcfTest.DocFlowWCF.Department))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(CallWcfTest.DocFlowWCF.Organization[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(CallWcfTest.DocFlowWCF.Organization))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(CallWcfTest.DocFlowWCF.EmployeeInfo[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(CallWcfTest.DocFlowWCF.EmployeeInfo))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(CallWcfTest.DocFlowWCF.LetterTemplate[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(CallWcfTest.DocFlowWCF.LetterTemplate))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Tuple<CallWcfTest.DocFlowWCF.DocFlowInfo[], int>))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(CallWcfTest.DocFlowWCF.BaseInfo))]
    public partial class SaveResult : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrorCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private object SaveDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SaveMessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool SaveStatusField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorCode {
            get {
                return this.ErrorCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorCodeField, value) != true)) {
                    this.ErrorCodeField = value;
                    this.RaisePropertyChanged("ErrorCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public object SaveData {
            get {
                return this.SaveDataField;
            }
            set {
                if ((object.ReferenceEquals(this.SaveDataField, value) != true)) {
                    this.SaveDataField = value;
                    this.RaisePropertyChanged("SaveData");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SaveMessage {
            get {
                return this.SaveMessageField;
            }
            set {
                if ((object.ReferenceEquals(this.SaveMessageField, value) != true)) {
                    this.SaveMessageField = value;
                    this.RaisePropertyChanged("SaveMessage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool SaveStatus {
            get {
                return this.SaveStatusField;
            }
            set {
                if ((this.SaveStatusField.Equals(value) != true)) {
                    this.SaveStatusField = value;
                    this.RaisePropertyChanged("SaveStatus");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="DocFlowWCF.IDocFlow")]
    public interface IDocFlow {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDocFlow/SearchAllDocs", ReplyAction="http://tempuri.org/IDocFlow/SearchAllDocsResponse")]
        System.Tuple<CallWcfTest.DocFlowWCF.DocFlowInfo[], int> SearchAllDocs(CallWcfTest.DocFlowWCF.DocSearchParameters _prms, int _pageIndex);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDocFlow/SearchAllDocs", ReplyAction="http://tempuri.org/IDocFlow/SearchAllDocsResponse")]
        System.Threading.Tasks.Task<System.Tuple<CallWcfTest.DocFlowWCF.DocFlowInfo[], int>> SearchAllDocsAsync(CallWcfTest.DocFlowWCF.DocSearchParameters _prms, int _pageIndex);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDocFlow/AssignDocToEmployee", ReplyAction="http://tempuri.org/IDocFlow/AssignDocToEmployeeResponse")]
        string AssignDocToEmployee(string employeeCode, string docNo, string docYear, string recpCode, string ftyCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDocFlow/AssignDocToEmployee", ReplyAction="http://tempuri.org/IDocFlow/AssignDocToEmployeeResponse")]
        System.Threading.Tasks.Task<string> AssignDocToEmployeeAsync(string employeeCode, string docNo, string docYear, string recpCode, string ftyCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDocFlow/GetDepartments", ReplyAction="http://tempuri.org/IDocFlow/GetDepartmentsResponse")]
        CallWcfTest.DocFlowWCF.Department[] GetDepartments();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDocFlow/GetDepartments", ReplyAction="http://tempuri.org/IDocFlow/GetDepartmentsResponse")]
        System.Threading.Tasks.Task<CallWcfTest.DocFlowWCF.Department[]> GetDepartmentsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDocFlow/GetOrganizations", ReplyAction="http://tempuri.org/IDocFlow/GetOrganizationsResponse")]
        CallWcfTest.DocFlowWCF.Organization[] GetOrganizations();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDocFlow/GetOrganizations", ReplyAction="http://tempuri.org/IDocFlow/GetOrganizationsResponse")]
        System.Threading.Tasks.Task<CallWcfTest.DocFlowWCF.Organization[]> GetOrganizationsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDocFlow/GetConfirmationUsers", ReplyAction="http://tempuri.org/IDocFlow/GetConfirmationUsersResponse")]
        CallWcfTest.DocFlowWCF.EmployeeInfo[] GetConfirmationUsers(int _dirCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDocFlow/GetConfirmationUsers", ReplyAction="http://tempuri.org/IDocFlow/GetConfirmationUsersResponse")]
        System.Threading.Tasks.Task<CallWcfTest.DocFlowWCF.EmployeeInfo[]> GetConfirmationUsersAsync(int _dirCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDocFlow/GetDocInfo", ReplyAction="http://tempuri.org/IDocFlow/GetDocInfoResponse")]
        CallWcfTest.DocFlowWCF.DocFlowInfo GetDocInfo(int docNo, int docYear);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDocFlow/GetDocInfo", ReplyAction="http://tempuri.org/IDocFlow/GetDocInfoResponse")]
        System.Threading.Tasks.Task<CallWcfTest.DocFlowWCF.DocFlowInfo> GetDocInfoAsync(int docNo, int docYear);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDocFlow/LoadLetterTemplates", ReplyAction="http://tempuri.org/IDocFlow/LoadLetterTemplatesResponse")]
        CallWcfTest.DocFlowWCF.LetterTemplate[] LoadLetterTemplates();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDocFlow/LoadLetterTemplates", ReplyAction="http://tempuri.org/IDocFlow/LoadLetterTemplatesResponse")]
        System.Threading.Tasks.Task<CallWcfTest.DocFlowWCF.LetterTemplate[]> LoadLetterTemplatesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDocFlow/SaveLetterTemplate", ReplyAction="http://tempuri.org/IDocFlow/SaveLetterTemplateResponse")]
        CallWcfTest.DocFlowWCF.SaveResult SaveLetterTemplate(CallWcfTest.DocFlowWCF.LetterTemplate _letterTemplate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDocFlow/SaveLetterTemplate", ReplyAction="http://tempuri.org/IDocFlow/SaveLetterTemplateResponse")]
        System.Threading.Tasks.Task<CallWcfTest.DocFlowWCF.SaveResult> SaveLetterTemplateAsync(CallWcfTest.DocFlowWCF.LetterTemplate _letterTemplate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDocFlow/LoadLetterTemplate", ReplyAction="http://tempuri.org/IDocFlow/LoadLetterTemplateResponse")]
        CallWcfTest.DocFlowWCF.LetterTemplate LoadLetterTemplate(int _templateCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDocFlow/LoadLetterTemplate", ReplyAction="http://tempuri.org/IDocFlow/LoadLetterTemplateResponse")]
        System.Threading.Tasks.Task<CallWcfTest.DocFlowWCF.LetterTemplate> LoadLetterTemplateAsync(int _templateCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDocFlow/AddDocumentTransfer", ReplyAction="http://tempuri.org/IDocFlow/AddDocumentTransferResponse")]
        CallWcfTest.DocFlowWCF.SaveResult AddDocumentTransfer(CallWcfTest.DocFlowWCF.DocFlowInfo _doc);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDocFlow/AddDocumentTransfer", ReplyAction="http://tempuri.org/IDocFlow/AddDocumentTransferResponse")]
        System.Threading.Tasks.Task<CallWcfTest.DocFlowWCF.SaveResult> AddDocumentTransferAsync(CallWcfTest.DocFlowWCF.DocFlowInfo _doc);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDocFlow/SubmitTransfer", ReplyAction="http://tempuri.org/IDocFlow/SubmitTransferResponse")]
        CallWcfTest.DocFlowWCF.SaveResult SubmitTransfer(string _referenceNo, int _transferNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDocFlow/SubmitTransfer", ReplyAction="http://tempuri.org/IDocFlow/SubmitTransferResponse")]
        System.Threading.Tasks.Task<CallWcfTest.DocFlowWCF.SaveResult> SubmitTransferAsync(string _referenceNo, int _transferNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDocFlow/SearchFollowDocuments", ReplyAction="http://tempuri.org/IDocFlow/SearchFollowDocumentsResponse")]
        CallWcfTest.DocFlowWCF.DocFlowInfo[] SearchFollowDocuments(CallWcfTest.DocFlowWCF.DocSearchParameters _prms);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDocFlow/SearchFollowDocuments", ReplyAction="http://tempuri.org/IDocFlow/SearchFollowDocumentsResponse")]
        System.Threading.Tasks.Task<CallWcfTest.DocFlowWCF.DocFlowInfo[]> SearchFollowDocumentsAsync(CallWcfTest.DocFlowWCF.DocSearchParameters _prms);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IDocFlowChannel : CallWcfTest.DocFlowWCF.IDocFlow, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DocFlowClient : System.ServiceModel.ClientBase<CallWcfTest.DocFlowWCF.IDocFlow>, CallWcfTest.DocFlowWCF.IDocFlow {
        
        public DocFlowClient() {
        }
        
        public DocFlowClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DocFlowClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DocFlowClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DocFlowClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Tuple<CallWcfTest.DocFlowWCF.DocFlowInfo[], int> SearchAllDocs(CallWcfTest.DocFlowWCF.DocSearchParameters _prms, int _pageIndex) {
            return base.Channel.SearchAllDocs(_prms, _pageIndex);
        }
        
        public System.Threading.Tasks.Task<System.Tuple<CallWcfTest.DocFlowWCF.DocFlowInfo[], int>> SearchAllDocsAsync(CallWcfTest.DocFlowWCF.DocSearchParameters _prms, int _pageIndex) {
            return base.Channel.SearchAllDocsAsync(_prms, _pageIndex);
        }
        
        public string AssignDocToEmployee(string employeeCode, string docNo, string docYear, string recpCode, string ftyCode) {
            return base.Channel.AssignDocToEmployee(employeeCode, docNo, docYear, recpCode, ftyCode);
        }
        
        public System.Threading.Tasks.Task<string> AssignDocToEmployeeAsync(string employeeCode, string docNo, string docYear, string recpCode, string ftyCode) {
            return base.Channel.AssignDocToEmployeeAsync(employeeCode, docNo, docYear, recpCode, ftyCode);
        }
        
        public CallWcfTest.DocFlowWCF.Department[] GetDepartments() {
            return base.Channel.GetDepartments();
        }
        
        public System.Threading.Tasks.Task<CallWcfTest.DocFlowWCF.Department[]> GetDepartmentsAsync() {
            return base.Channel.GetDepartmentsAsync();
        }
        
        public CallWcfTest.DocFlowWCF.Organization[] GetOrganizations() {
            return base.Channel.GetOrganizations();
        }
        
        public System.Threading.Tasks.Task<CallWcfTest.DocFlowWCF.Organization[]> GetOrganizationsAsync() {
            return base.Channel.GetOrganizationsAsync();
        }
        
        public CallWcfTest.DocFlowWCF.EmployeeInfo[] GetConfirmationUsers(int _dirCode) {
            return base.Channel.GetConfirmationUsers(_dirCode);
        }
        
        public System.Threading.Tasks.Task<CallWcfTest.DocFlowWCF.EmployeeInfo[]> GetConfirmationUsersAsync(int _dirCode) {
            return base.Channel.GetConfirmationUsersAsync(_dirCode);
        }
        
        public CallWcfTest.DocFlowWCF.DocFlowInfo GetDocInfo(int docNo, int docYear) {
            return base.Channel.GetDocInfo(docNo, docYear);
        }
        
        public System.Threading.Tasks.Task<CallWcfTest.DocFlowWCF.DocFlowInfo> GetDocInfoAsync(int docNo, int docYear) {
            return base.Channel.GetDocInfoAsync(docNo, docYear);
        }
        
        public CallWcfTest.DocFlowWCF.LetterTemplate[] LoadLetterTemplates() {
            return base.Channel.LoadLetterTemplates();
        }
        
        public System.Threading.Tasks.Task<CallWcfTest.DocFlowWCF.LetterTemplate[]> LoadLetterTemplatesAsync() {
            return base.Channel.LoadLetterTemplatesAsync();
        }
        
        public CallWcfTest.DocFlowWCF.SaveResult SaveLetterTemplate(CallWcfTest.DocFlowWCF.LetterTemplate _letterTemplate) {
            return base.Channel.SaveLetterTemplate(_letterTemplate);
        }
        
        public System.Threading.Tasks.Task<CallWcfTest.DocFlowWCF.SaveResult> SaveLetterTemplateAsync(CallWcfTest.DocFlowWCF.LetterTemplate _letterTemplate) {
            return base.Channel.SaveLetterTemplateAsync(_letterTemplate);
        }
        
        public CallWcfTest.DocFlowWCF.LetterTemplate LoadLetterTemplate(int _templateCode) {
            return base.Channel.LoadLetterTemplate(_templateCode);
        }
        
        public System.Threading.Tasks.Task<CallWcfTest.DocFlowWCF.LetterTemplate> LoadLetterTemplateAsync(int _templateCode) {
            return base.Channel.LoadLetterTemplateAsync(_templateCode);
        }
        
        public CallWcfTest.DocFlowWCF.SaveResult AddDocumentTransfer(CallWcfTest.DocFlowWCF.DocFlowInfo _doc) {
            return base.Channel.AddDocumentTransfer(_doc);
        }
        
        public System.Threading.Tasks.Task<CallWcfTest.DocFlowWCF.SaveResult> AddDocumentTransferAsync(CallWcfTest.DocFlowWCF.DocFlowInfo _doc) {
            return base.Channel.AddDocumentTransferAsync(_doc);
        }
        
        public CallWcfTest.DocFlowWCF.SaveResult SubmitTransfer(string _referenceNo, int _transferNumber) {
            return base.Channel.SubmitTransfer(_referenceNo, _transferNumber);
        }
        
        public System.Threading.Tasks.Task<CallWcfTest.DocFlowWCF.SaveResult> SubmitTransferAsync(string _referenceNo, int _transferNumber) {
            return base.Channel.SubmitTransferAsync(_referenceNo, _transferNumber);
        }
        
        public CallWcfTest.DocFlowWCF.DocFlowInfo[] SearchFollowDocuments(CallWcfTest.DocFlowWCF.DocSearchParameters _prms) {
            return base.Channel.SearchFollowDocuments(_prms);
        }
        
        public System.Threading.Tasks.Task<CallWcfTest.DocFlowWCF.DocFlowInfo[]> SearchFollowDocumentsAsync(CallWcfTest.DocFlowWCF.DocSearchParameters _prms) {
            return base.Channel.SearchFollowDocumentsAsync(_prms);
        }
    }
}
