ej.RTE.Locale["de-DE"] = {
                bold: "fett",
                italic: "kursiv",
                underline: "unterstreichen",
                strikethrough: "Durchgestrichen",
				superscript: "Überschrift",
				subscript: "Index",					
                justifyCenter: "Text-Zentrum",
                justifyLeft: "Ausrichten von Text links",
                justifyRight: "Ausrichten von Text rechts",
                justifyFull: "rechtfertigen",
                fileBrowser: "Datei-Browser",
                unorderedList: "Legen Sie ungeordnete Liste",
                orderedList: "Geordnete Liste einfugen",
                indent: "Einzug",
                outdent: "Einzug verkleinern",
                undo: "lösen",
                redo: "Wiederherstellen",
                clearAll: "Alles",
                clearFormat: "Klar Format",
                createLink: "Einfugen / Hyperlink Bearbeiten",
				removeLink:"fjern Hyperlink",
                image: "Bild einfugen",
                video: "Legen Video",
                embedVideo: "Fugen Sie den Embed-Code unten",
                viewHtml: "Blick HTML",
                deleteAlert: "Sind Sie sicher, dass Sie alle Inhalte löschen?",
                videoError: "Der Textbereich darf nicht leer sein",
                imageWebUrl: "Web-URL",
                imageAltText: "Bildbeschreibung",
                dimensions: "Größe",
                constrainProportions: "Proportionen",
                linkWebUrl: "Web-URL",
                linkText: "Text",
                linkToolTip: "Quickinfo",
                html5Support: "Dieses Werkzeug-Symbol nur in HTML5 aktiviert unterstützten Browser",
                linkOpenInNewWindow: "Link in einem neuen Fenster",
                solid:"solide",
			    dashed:"gestippelde",
			    dotted:"stippel",
			    doubled:"dubbele",
			    buttonApply:"toepassen",
			    buttonCancel:"annuleren",
			    closeIcon:"dicht",
                tableColumns: "Spalten",
                tableRows: "Zeilen",
                tableWidth: "Tischbreite",
                tableHeight: "Tischhöhe",
                tableCellSpacing: "cellspacing",
                tableCellPadding: "cellpadding",
                tableBorder: "Grenze",
                tableCaption: "Beschriftung",
                tableAlignment: "Ausrichtung",
                dialogUpdate: "Aktualisierung",
                dialogInsert: "einfugen",
                dialogCancel: "stornieren",
                dialogOk: "Ok",
                createTable: "Tabelle erstellen",
                addColumnLeft: "Spalte links hinzufugen",
                addColumnRight: "In Spalte auf der rechten",
                addRowAbove: "Zeile hinzufugen oben",
                addRowBelow: "Zeile hinzufugen unten",
                deleteRow: "Löschen Sie die Zeile",
                deleteColumn: "Löschen Sie die Spalte",
                deleteTable: "Löschen Sie die Tabelle",
                customTable: "von benutzerdefinierten Tabelle",
                characters: "Charaktere",
                dialogApply: "anwenden",
                textAlign: "Text ausrichten",
                imageLink: "Bild als Link zu",
                imageBorder: "Bild Rand",
                imageStyle: "Stil",
                editTable: "Tabelle Eigenschaften bearbeiten",
                general: "allgemein",
                advanced: "fortgeschritten",
                table: "Tisch",
                row: "Reihe",
                column: "Spalte",
                cell: "Zelle",
			    maximize:"Maximieren",
		        resize: "Minimieren",
			    swatches: "Farbfelder"
            };

      ej.RTE.Locale["es-ES"] = {
                bold: "audaz",
                italic: "itálico",
                underline: "subrayar",
                strikethrough: "Tachado",
				superscript: "sobrescrito",
				subscript: "subíndice",					
                justifyCenter: "Centrar texto",
                justifyLeft: "Alinear texto a la izquierda",
                justifyRight: "Alinear texto a la derecha",
                justifyFull: "justificar",
                fileBrowser: "archivo Browser",
                unorderedList: "Inserte lista desordenada",
                orderedList: "Insertar lista ordenada",
                solid: "solida",
                dashed: "fraŭditaj",
                dotted: "punktita",
                doubled: "duobla",
                closeIcon: "Fermi",
                buttonApply: "apliki",
                buttonCancel: "nuligi",
                indent: "muesca",
                outdent: "reducir sangría",
                undo: "deshacer",
                redo: "rehacer",
                clearAll: "Borrar todo",
                clearFormat: "Claro Formato",
                createLink: "Insertar / Editar hipervínculo",
				removeLink:"quitar hipervínculo",
                image: "insertar una imagen",
                video: "insertar vídeo",
                embedVideo: "Pegue su código de inserción por debajo de",
                viewHtml: "Ver HTML",
                format: "formato",
                deleteAlert: "¿Está seguro que desea borrar todo el contenido?",
                copyPastAlert: "Your browser doesn't support direct access to the clipboard. Please use the Ctrl+X/C/V keyboard shortcuts instead.",
                videoError: "El área de texto no puede estar vacío",
                imageWebUrl: "URL web",
                imageAltText: "Descripción",
                dimensions: "dimensiones",
                constrainProportions: "Restringir proporciones",
                linkWebUrl: "URL web",
                linkText: "texto",
                linkToolTip: "ToolTip",
                html5Support: "Este icono de la herramienta sólo disponible en HTML5 apoyó navegadores",
                linkOpenInNewWindow: "Abrir enlace en una nueva ventana",
                tableColumns: "Columnas No.of",
                tableRows: "Numero de Filas",
                tableWidth: "ancho de la mesa",
                tableHeight: "altura de la mesa",
                tableCellSpacing: "El espaciado",
                tableCellPadding: "Relleno",
                tableBorder: "frontera",
                tableCaption: "subtítulo",
                tableAlignment: "alineación",
                dialogUpdate: "actualización",
                dialogInsert: "insertar",
                dialogCancel: "cancelar",
                dialogOk: "bueno",
                createTable: "Crear una tabla",
                addColumnLeft: "Añadir la columna de la izquierda",
                addColumnRight: "Añadir columna a la derecha",
                addRowAbove: "Añadir fila encima",
                addRowBelow: "Añadir fila abajo",
                deleteRow: "Elimine la fila",
                deleteColumn: "Eliminar la columna",
                deleteTable: "Eliminar la tabla",
                customTable: "Crear una tabla personalizada",
                characters: "Personajes",
                dialogApply: "aplicar",
                textAlign: "Texto Alinear",
                imageLink: "Imagen como Enlace",
                imageBorder: "Imagen de fronteras",
                imageStyle: "Estilo",
                editTable: "Editar las propiedades de la tabla",
                general: "corriente",
                advanced: "avanzada",
                table: "tabla",
                row: "fila",
                column: "columna",
                cell: "célula",
			    maximize:"Maximizar",
		        resize: "Minimizar",
			    swatches: "Muestras"
            };

            var format_DE = [
                { text: "Absatz", value: "<p>", spriteCSS: "e-paragraph" },
                { text: "Zitat", value: "<blockquote>", spriteCSS: "e-quotation" },
                { text: "Kopf 1", value: "<h1>", spriteCSS: "e-h1" },
                { text: "Kopf 2", value: "<h2>", spriteCSS: "e-h2" },
                { text: "Kopf 3", value: "<h3>", spriteCSS: "e-h3" },
                { text: "Kopf 4", value: "<h4>", spriteCSS: "e-h4" },
                { text: "Kopf 5", value: "<h5>", spriteCSS: "e-h5" },
                { text: "Kopf 6", value: "<h6>", spriteCSS: "e-h6" }
            ];

            var format_ES = [
        { text: "acápite", value: "<p>", spriteCSS: "e-paragraph" },
        { text: "cita", value: "<blockquote>", spriteCSS: "e-quotation" },
        { text: "título 1", value: "<h1>", spriteCSS: "e-h1" },
        { text: "título 2", value: "<h2>", spriteCSS: "e-h2" },
        { text: "título 3", value: "<h3>", spriteCSS: "e-h3" },
        { text: "título 4", value: "<h4>", spriteCSS: "e-h4" },
        { text: "título 5", value: "<h5>", spriteCSS: "e-h5" },
        { text: "título 6", value: "<h6>", spriteCSS: "e-h6" }
            ];

            var format = [
                 { text: "Paragraph", value: "<p>", spriteCSS: "e-paragraph" },
                 { text: "Quotation", value: "<blockquote>", spriteCSS: "e-quotation" },
                 { text: "Heading 1", value: "<h1>", spriteCSS: "e-h1" },
                 { text: "Heading 2", value: "<h2>", spriteCSS: "e-h2" },
                 { text: "Heading 3", value: "<h3>", spriteCSS: "e-h3" },
                 { text: "Heading 4", value: "<h4>", spriteCSS: "e-h4" },
                 { text: "Heading 5", value: "<h5>", spriteCSS: "e-h5" },
                 { text: "Heading 6", value: "<h6>", spriteCSS: "e-h6" }
            ];
                     $(function () {
                         $("#sampleProperties").ejPropertiesPanel();
                     });

            
            function onChange(args) {
                var newFormat = args.value == "de-DE" ? format_DE : (args.value == "es-ES" ? format_ES : format);
                $("#LayoutSection_ControlsSection_rteSample").ejRTE("model.format", newFormat);
                $("#LayoutSection_ControlsSection_rteSample").ejRTE("model.locale", args.value);
            }